<section class="h-screen w-screen flex justify-center items-center flex-col">
    <form action="/auth/register" method="post" class="capitalize text-slate-600 flex justify-center items-center flex-col">
        <label for="icon" class="bg-gradient-to-r from-indigo-500 to-cyan-600  bg-clip-text text-transparent">
            <i class="fa fa-fire text-9xl"></i>
        </label>
        <label for="name" class="mt-2">
            <p><i class="fa fa-user bg-gradient-to-r from-indigo-500 to-cyan-600 bg-clip-text text-transparent"></i> name</p>
            <input type="text" name="name" id="name" placeholder="name" class="border-2 border-stone-700 rounded-sm mt-2" required>
        </label>
            <?php
            if (isset($errors)) {
                if (isset($errors["name"])) {
            ?>
                    <span class="text-xs w-full text-left text-red-500">* <?php echo $errors["name"]; ?></span>
            <?php
                }
            }
            ?>
        <label for="email" class="mt-2">
            <p><i class="fa fa-envelope-open bg-gradient-to-r from-indigo-500 to-cyan-600 bg-clip-text text-transparent"></i> email</p>
            <input type="email" name="email" id="email" placeholder="email" class="border-2 border-stone-700 rounded-sm mt-2" required>
        </label>
        <?php
        if (isset($errors)) {
            if (isset($errors["email"])) {
        ?>
                <span class="text-xs w-full text-left text-red-500">* <?php echo $errors["email"]; ?></span>
        <?php
            }
        }
        ?>
        <label for="password" class="mt-2">
            <p><i class="fa fa-lock bg-gradient-to-r from-indigo-500 to-cyan-600  bg-clip-text text-transparent"></i> password</p>
            <input type="password" name="password" id="password" placeholder="password" class="border-2 border-stone-700 rounded-sm mt-2" required>
        </label>
        <?php
        if (isset($errors)) {
            if (isset($errors["password"])) {
        ?>
                <span class="text-xs w-full text-left text-red-500">* <?php echo $errors["password"]; ?></span>
        <?php
            }
        }
        ?>
        <label for="submit" class="w-full my-4">
            <input type="submit" value="Register" name="submit" id="name" class="w-full p-2 rounded-sm shadow-md cursor-pointer text-white bg-gradient-to-r from-indigo-500 to-cyan-600 ">
        </label>
        <?php
        if (isset($message)) {
        ?>
            <p class="text-red-500 font-medium bg-indigo-200 w-full p-3 rounded-sm text-center">
                <?php
                echo $message;
                ?>
            </p>
        <?php
        }
        ?>
    </form>
</section>